// node('dev') {
//     // Define environment variable
//     def imageName = 'edmundtetteh/movies-parser'
//     def registry = 'https://registry.slowcoder.com'

//     // Stage: Checkout
//     stage('Checkout') {
//         // Git checkout
//         checkout([$class: 'GitSCM', branches: [[name: 'develop']],
//                   userRemoteConfigs: [[url: 'git@github.com:edmundtetteh/weather-app-project.git']],
//                   credentialsId: 'ssh-togithub'])
//     }
// }


pipeline {
    agent {
        label 'dev'
    }

    environment {
        imageName = 'edmundtetteh/movies-parser'
        registry = 'https://registry.slowcoder.com'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                          userRemoteConfigs: [[url: 'git@github.com:edmundtetteh/weather-app-project.git']]])
            }
        }
    }
}